version: '2.1'
services:

    webapp:
        image: node:9.9
        networks:
            - development
        ports:
            - ${APP_PORT:-3000}:3000
            - ${SSR_PORT:-8080}:8080
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            LOG_LEVEL: ${LOG_LEVEL:-verbose}
            SSR_PORT: ${SSR_PORT:-8080}
            SSR_ROOT: ${SSR_ROOT:-/usr/src/app/src}
            SSR_BUILD: ${SSR_ROOT:-/usr/src/app/build}
        volumes:
            - ./services/webapp:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev" ]

networks:
    development:
